### PR TITLE
Support create comment on pull_request_target event

### PR DESCRIPTION
**Pull request by jhen0409**
The [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event is similar to `pull_request` but allows specific activity types. In my case, I want to limit the trigger to `[opened, synchronize]`.

### CODE REVIEW

**Comment by balaji-nordic** [comment]
I just created https://github.com/zgosalvez/github-actions-report-lcov/pull/25 . See my reasonings in the PR. Will the changes in this PR work the same way as mine? Because the event is always non-null (non-empty) when the work flow is triggered? So we might as well drop the check on the event name itself?

**Comment by balaji-nordic** [comment]
@jhen0409  By the way, you have not uploaded the generated files under dist folder. My understanding is that that we need those files to for the github actions to work. My PRs all contain those files. May be I have misunderstood something?

**Comment by jhen0409** [comment]
> @jhen0409 By the way, you have not uploaded the generated files under dist folder. My understanding is that that we need those files to for the github actions to work. My PRs all contain those files. May be I have misunderstood something?

I hope the the PR can be reduced the review noises, so I expected it can be build when release new version.

> I just created #25 . See my reasonings in the PR. Will the changes in this PR work the same way as mine? Because the event is always non-null (non-empty) when the work flow is triggered? So we might as well drop the check on the event name itself?

I saw #25 I think it will broke the workflow on another trigger types, because it not always have pr number on every trigger type.

**Comment by balaji-nordic** [comment]
> I hope the PR can be reduced the review noises, so I expected it can be build when release new version.

Ah got it.

> I saw https://github.com/zgosalvez/github-actions-report-lcov/pull/25 I think it will broke the workflow on another trigger types, because it not always have pr number on every trigger types.

I dont think I understand the comment. But I think you prefer to get the PR number for ever comment. Is that correct?

**Comment by jhen0409** [comment]
> I dont think I understand the comment. But I think you prefer to get the PR number for ever comment. Is that correct?

I mean `github.context.payload.pull_request`, it doesn't exist on trigger types like `push`. In case if I just want to update artifact without create comment, I will use the trigger type like that.

**Comment by zgosalvez** [comment]
Hello everyone. I just want to make sure I'm processing the right PR. So in lieu of this PR, #25 can be merged and this can be closed?

**Comment by jhen0409** [comment]
> Hello everyone. I just want to make sure I'm processing the right PR. So in lieu of this PR, #25 can be merged and this can be closed?

It might depend on the use case like I saw in https://github.com/zgosalvez/github-actions-report-lcov/pull/22#issuecomment-1160115960.

However, [these](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_comment-use-issue_comment) more trigger types may includes the payload. The best way probably is skip create comment when the payload is empty.

**Comment by balaji-nordic** [comment]
From my side, I dont mind creation of multiple comments. Creation of a comment is a minor action and it does not take long. And I can also manually delete comments that are not needed. But this is just my use case. 

The primary goal of https://github.com/zgosalvez/github-actions-report-lcov/pull/25 is that if I update my PR with more unit tests and the coverage improves, I want it to show up as a comment. If that is achieved in a better way, I will be happy to accept the solution.

**Comment by balaji-nordic** [comment]
Note the PR https://github.com/zgosalvez/github-actions-report-lcov/pull/28 . This allows us to skip creating multiple comments. :-)

**Comment by zgosalvez** [comment]
Thank you for your patience and contribution. I'm kind of lost in the conversation but I've decided to merge this relatively straightforward PR. Thank you again!

**Pull request merged**
