### PR TITLE
Implement macOS support

### PR DESCRIPTION
**Pull request by koddsson**
Here's my attempt to implement macOS support. We check `os.platform()` and change the install `lcov` using brew instead of `apt-get`.

### CODE REVIEW

**Review by mvolpato — COMMENTED** [review]
Why so many changes in generated files?

**Comment by mvolpato** [comment]
@zgosalvez any chance to have this reviewed?

**Comment by zgosalvez** [comment]
Hi @mvolpato and @koddsson. Thank you for this. I'm just wondering what your thoughts are on just running the install code before this action is executed. As mentioned in the README file, this expects that there are prior steps to "# ... Generate LCOV files or download it from a different job"

I mean, your PR is relatively straightforward. I'm trying to mirror how other actions are relatively doing just one thing. For example, there's a specific GitHub Action just to install Node, which the dev is expected to run first before using other actions/commands that depend on it.

**Comment by zgosalvez** [comment]
P.S. I'm thinking of just removing the installation of LCOV altogether and leaving that to the developer to run before using this action. We can also create a new GitHub Action to install LCOV with support for any platform. Thoughts? CC: @LeKristapino

**Comment by mvolpato** [comment]
> Hi @mvolpato and @koddsson. Thank you for this. I'm just wondering what your thoughts are on just running the install code before this action is executed. As mentioned in the README file, this expects that there are prior steps to "# ... Generate LCOV files or download it from a different job"

That is fine!

**Comment by zgosalvez** [comment]
Ok. Let's have this for the v3 release since this is a breaking change. I want to get @koddsson's vote on this too. Thanks, @mvolpato!

**Comment by koddsson** [comment]
> Ok. Let's have this for the v3 release since this is a breaking change. I want to get @koddsson's vote on this too. Thanks, @mvolpato!

Sure sounds good to me. Should I just close this PR or update it somehow? I'm currently just running a fork of this action in my project so there's no rush on my end.

**Comment by zgosalvez** [comment]
@koddsson and @mvolpato, would you guys mind testing the new PR #45 with the updated workflow:
```yml
- name: Setup LCOV
  uses: hrishikesh-kadam/setup-lcov@v1
```

**Pull request closed without merging**
