### PR TITLE
Option to update the PR comment – improvements

### PR DESCRIPTION
**Pull request by bartosz347**
I've rebased the PR https://github.com/zgosalvez/github-actions-report-lcov/pull/28 created by @oacik and applied some improvements to properly handle `minimum-coverage` check.

I've tested the changes in a test repository – https://github.com/bartosz347/github-actions-flutter-workflows/pull/1. The build is failing intentionally – to test minimum coverage requirement. I've tested the following scenarios:
1. Current version, minimum coverage requirement satisfied
2. Current version, minimum coverage requirement not satisfied
3. Updated version, minimum coverage requirement satisfied
4. Updated version, minimum coverage requirement not satisfied
5. Updated version, minimum coverage requirement satisfied, `update-comment: false` (regression)

In both 3. and 4. the comment https://github.com/bartosz347/github-actions-flutter-workflows/pull/1#issuecomment-1325483698 has been updated. In 5. new comment has been created.

If there's any better way to contribute to the previous PR, please let me know. Thanks @oacik for your work!

### CODE REVIEW

**Comment by zgosalvez** [comment]
Hi @bartosz347! Curious why you didn't simply contribute to the original PR #28?

**Comment by bartosz347** [comment]
Hey @zgosalvez, that's what I've wanted to do at first, but I think I can't contribute to the existing PR – I'd have to push to its author's repository (I don't have RW access). Only maintainers are allowed to add new commits. Or maybe I'm wrong – please tell me how can I do this :)

**Comment by zgosalvez** [comment]
Oh yeah, I forgot. 😅 Well, I did take a look at your PR and it appears to be somewhat unrelated to #28, right? #28 is simply about providing the option to update a comment instead of creating a new one. Whereas your PR here is an improvement on minimum coverage, correct?

**Comment by bartosz347** [comment]
Not exactly, #28 has a return statement which omits `isFailure` check (see https://github.com/zgosalvez/github-actions-report-lcov/pull/28/files#r935143815) – I believe minimum code coverage condition does not work properly in #28.

**Comment by bartosz347** [comment]
Hey @zgosalvez looks like something's wrong with [Build & Test](https://github.com/zgosalvez/github-actions-report-lcov/actions/runs/3905774504/jobs/6673186177#logs) pipeline, it can't check out code from fork. Would you be able to fix this and merge my PR?

**Comment by kdawgwilk** [comment]
Would love to see this addition and fixes for v3!

**Comment by zgosalvez** [comment]
Addressed in #85 🚀

**Pull request closed without merging**
