### PR TITLE
Fixes and improvements to v3

### PR DESCRIPTION
**Pull request by bartosz347**
I'm aware that it might not be a best approach to propose all changes at once, but my previous PR is waiting quite long and wanted to keep this project going.

Fixes/reverts to make v3 usable
 - [Adjust to changes in GitHub API package](https://github.com/zgosalvez/github-actions-report-lcov/commit/26ece76e6d53dc5d59a5b3a2fb98e192eab4de2b)
 - [Revert to previous lcov-total version to support CommonJS](https://github.com/zgosalvez/github-actions-report-lcov/commit/7dbbe835bfbfe5f36b2e1dcad073353a9cf8ca98)

New features
- Defining custom message added to comment
- Option to update the PR comment instead of creating a new one

### CODE REVIEW

**Comment by zgosalvez** [comment]
Hi! So sorry for missing out on people's issues and PRs! I'd like to confirm a few things:

- Can we close #42 in lieu of this PR?
- Does this resolve #61?

**Comment by bartosz347** [comment]
Hi, yes, both points are correct :)

**Comment by zgosalvez** [comment]
Cool! I'll clean up and review in the next few hours 🙂 I appreciate everyone's patience. 😅

**Comment by zgosalvez** [comment]
I'm not sure how we can avoid `lcov-total` from breaking the action again in the future. Feel free to build on #87, even just for catching the issue with ESM.

**Pull request merged**
